[general]
connection = "Data Source=sample.db"
output = "./SqlHydra.Generated.fs"
namespace = "MyWebApi.Data.SqlHydraGenerated"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
table_declarations = true
[readers]
reader_type = "Microsoft.Data.Sqlite.SqliteDataReader"